version: "3.4"

services:
  nginx:
    env_file: .env
    container_name: nginx
    image: my_docker_registry:latest
    restart: unless-stopped 
    build:
      context: ./nginx
      args:
        - REGISTRY_USER=${REGISTRY_USER}
        - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
        - DOMAIN=${VIRTUAL_HOST}
    expose:
      - 80
    networks:
      - default
      - docker-registry
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"

  registry:
    container_name: registry
    image: registry:2
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      - docker-registry
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"
   

networks:
  default:
    external:
      name: reverse-proxy
  docker-registry:
     driver: bridge
